name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Generate Datas
    runs-on: ubuntu-latest
    steps:
      # Replace this with your actual data generation commands
      - run: |
          # Example: Generate data using Python
          python generate_data.py
        name: Generate Data

      # Publish to GitHub Pages (optional)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          # Use a more secure way to access secrets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
